# Generated by Django 5.1 on 2024-11-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sapphires',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
