# Generated by Django 5.1 on 2024-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpares', '0002_traccia_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='traccia',
            name='partis_run',
            field=models.BooleanField(default=False),
        ),
    ]
