# Generated by Django 5.1 on 2024-12-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpares', '0005_alter_tema_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='traccia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temi', to='interpares.traccia'),
            preserve_default=False,
        ),
    ]
