# Generated by Django 5.1 on 2024-12-08 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpares', '0007_alter_tema_traccia_alter_tema_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='griglia',
            unique_together={('user', 'tema')},
        ),
    ]
