# Generated by Django 5.1 on 2024-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpares', '0008_alter_griglia_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='griglia',
            name='avreage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
