# Generated by Django 5.1 on 2024-08-23 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pawns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
                ('correct', models.CharField(max_length=128)),
                ('a1', models.CharField(max_length=128)),
                ('a2', models.CharField(max_length=128)),
                ('a3', models.CharField(max_length=128)),
                ('pawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pawns.pawn')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
