# Generated by Django 5.1 on 2024-08-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0001_initial'),
        ('quiz', '0002_alter_question_pawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pawn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pawns.pawn'),
        ),
    ]
