# Generated by Django 5.1 on 2024-08-25 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='state',
        ),
        migrations.AddField(
            model_name='answer',
            name='correctly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='wrongly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
