# Generated by Django 5.1 on 2024-09-11 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pawn_images/')),
                ('is_public', models.BooleanField(default=False)),
                ('quiz', models.BooleanField(default=False)),
                ('coze', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='pawns', to='auth.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='pawns.pawn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
                ('correct', models.CharField(max_length=128)),
                ('a1', models.CharField(max_length=128)),
                ('a2', models.CharField(max_length=128)),
                ('a3', models.CharField(max_length=128)),
                ('pawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pawns.pawn')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctly', models.IntegerField(default=0)),
                ('wrongly', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pawns.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='pawns.pawn')),
            ],
        ),
    ]
