# Generated by Django 5.1 on 2024-09-02 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=512, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pawn_images/')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('hide', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='pawns.pawn')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
                ('correct', models.CharField(max_length=128)),
                ('a1', models.CharField(max_length=128)),
                ('a2', models.CharField(max_length=128)),
                ('a3', models.CharField(max_length=128)),
                ('pawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pawns.pawn')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctly', models.IntegerField(default=0)),
                ('wrongly', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pawns.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='pawns.pawn')),
            ],
        ),
    ]
