# Generated by Django 5.1 on 2024-08-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
