# Generated by Django 5.1 on 2024-09-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='text',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
