# Generated by Django 5.1 on 2024-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0003_rename_value_link_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='link',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
