# Generated by Django 5.1 on 2024-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0004_pawn_link_delete_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='exam',
            field=models.BooleanField(default=False),
        ),
    ]
