# Generated by Django 5.1 on 2024-09-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0005_pawn_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='exam_count',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='pawn',
            name='exam_time',
            field=models.IntegerField(default=45),
        ),
    ]
