# Generated by Django 5.1 on 2024-09-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pawns', '0005_alter_pawn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='groups',
            field=models.ManyToManyField(related_name='pawns', to='auth.group'),
        ),
    ]
