# Generated by Django 5.1 on 2024-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0006_pawn_exam_count_pawn_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='wrongly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QuestionSubmitted',
        ),
    ]
