# Generated by Django 5.1 on 2024-09-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pawns', '0006_pawn_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawn',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='pawns', to='auth.group'),
        ),
    ]
