# Generated by Django 5.1 on 2024-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0007_question_correctly_question_wrongly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='open_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pawn',
            name='partis',
            field=models.BooleanField(default=False),
        ),
    ]
