# Generated by Django 5.1 on 2024-11-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0008_pawn_open_questions_pawn_partis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawn',
            name='open_questions',
        ),
    ]
