# Generated by Django 5.1 on 2024-11-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0009_remove_pawn_open_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('pawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openQuesions', to='pawns.pawn')),
            ],
        ),
    ]
