# Generated by Django 5.1 on 2024-09-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0012_remove_pawn_group_pawn_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawn',
            name='hide',
        ),
    ]
