# Generated by Django 5.1 on 2024-11-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pawns', '0013_judgequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='openanswer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
