# Generated by Django 5.1 on 2024-09-08 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0014_pawn_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawn',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
