# Generated by Django 5.1 on 2024-09-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0015_alter_pawn_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawn',
            name='slug',
        ),
    ]
