# Generated by Django 5.1 on 2024-11-22 08:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0017_alter_openanswer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openanswer',
            unique_together={('user', 'openQuestion')},
        ),
    ]
