# Generated by Django 5.1 on 2024-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0020_pawn_partis_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='correctAnswer',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
