# Generated by Django 5.1 on 2024-11-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0022_alter_judgequestion_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
