# Generated by Django 5.1 on 2024-11-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0023_pawn_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='explore',
            field=models.BooleanField(default=False),
        ),
    ]
