# Generated by Django 5.1 on 2024-11-30 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pawns', '0024_pawn_explore'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='editors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors', to='auth.group'),
        ),
    ]
