# Generated by Django 5.1 on 2024-11-30 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0025_pawn_editors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawn',
            name='editors',
        ),
        migrations.AddField(
            model_name='pawn',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editablePawns', to=settings.AUTH_USER_MODEL),
        ),
    ]
