# Generated by Django 5.1 on 2024-11-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawns', '0026_remove_pawn_editors_pawn_editors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pawn',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='pawn',
            old_name='is_public',
            new_name='public',
        ),
    ]
